name: AzPvp
version: '1.0-SNAPSHOT'
main: io.github.AzmiiD.azPvp.AzPvp
api-version: '1.21'
authors: [ Azmii_ ]
description: Pvp System Minecraft Server
commands:
  pvp:
    description: Toggle PVP mode
    usage: /pvp <on|off>
  azpvp:
    description: AZPvP admin commands
    usage: /azpvp reload
permissions:
  azpvp.bypass:
    description: Bypass combat command block
    default: op
  azpvp.reload:
    description: Reload config
    default: op